[tools]
node = "26"
python = "3.13"
ruby = "4.0"
awscli = "latest"
jq = "latest"
tfenv = "latest"
starship = "latest"
aqua = "latest"
delta = "latest"
gh = "latest"
fzf = "latest"
neovim = "latest"
ecspresso = "latest"
"aqua:fujiwara/lambroll" = "latest"
"npm:playwright-cli" = "latest"

[settings]

[settings.ruby]
compile = true
