include_role "base"

include_cookbook "git"
include_cookbook "bash"
include_cookbook "starship"
include_cookbook "tmux"
include_cookbook "nvim"
package "gh"
package "fzf"
include_cookbook "jq"
include_cookbook "rust"
include_cookbook "z"
include_cookbook "envchain"
include_cookbook "awscli"

include_cookbook "rbenv"
include_cookbook "nodenv"
