include_role "base"

include_cookbook "git"
include_cookbook "bash"
include_cookbook "starship"
include_cookbook "tmux"
include_cookbook "nvim"
include_cookbook "rust"
include_cookbook "z"
include_cookbook "envchain"
