#!/usr/bin/env bash

if [[ $# -ne 1 ]]; then
  echo 'Usage: commit-open <commit hash>'
  exit 2
fi

target_remote="upstream"
if ! git remote | grep "$target_remote"; then
  target_remote="origin"
fi

repository_path=$(git remote get-url "$target_remote" | sed -E 's/git@(.+):(.+)\/(.+)\.git/https:\/\/\1\/\2\/\3/')

open "$repository_path/commit/$1"
