#!/usr/bin/env bash

if [[ $# -gt 0 ]]; then
  git branch -D "$1"
else
  target_branch=$(git branch | cut -c3- | fzf --query="$1" --preview='git log {} -1')

  if [ -n "$target_branch" ]; then
    git branch -D "$target_branch"
  else
    echo "(っ･ω･)っ[Target branch not selected]"
  fi
fi
